name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7
      - name: Build image
        run: docker build -t api-app .
      - name: Run
        run: docker run -p 80:8080 api-app
      - name: Test
        uses: liatrio/github-actions/apprentice-action@master