name: Pipeline

on: push

jobs:
  pipeline:
    name: Build, Test, & Push
    runs-on: ubuntu-24.04
    env:
      IMAGE_TAG: ${{ vars.DOCKERHUB_USERNAME }}/api-app:${{ github.sha }}
    steps:
      - name: Pull source code
        uses: actions/checkout@v7
      - name: Build
        run: docker build -t $IMAGE_TAG .
      - name: Run
        run: docker run -d -p 80:8080 $IMAGE_TAG
      - name: Test
        uses: liatrio/github-actions/apprentice-action@0b41561cca6822cc8d880fe0e49e7807a41fdf91
      - name: Auth DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Image To DockerHub
        if: github.ref == 'refs/heads/main'
        run: docker push $IMAGE_TAG