name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull source code
        uses: actions/checkout@v7
      - name: Build
        run: docker build -t api-app .
      - name: Run
        run: docker run -d -p 80:8080 api-app
      - name: Test
        uses: liatrio/github-actions/apprentice-action@0b41561cca6822cc8d880fe0e49e7807a41fdf91